# 1.try-catch语句
    try{
      window.some();
    } catch (error) {
        console.log(error.message);
        console.log(error.name);
    }
如果try块中的任何代码发生了错误，就会立即退出代码执行过程，然后接着执行catch块。此时，catch块会接受到一个包含错误信息的对象。      
即使你不想使用这个错误对象，也要给它起个名字。但共同的是有一个保存着错误消息的message属性。还有一个name属性。    
![5Hj7GK.png](https://s1.ax2x.com/2018/09/24/5Hj7GK.png)  
###  finally子句
虽然在try-catch语句中是可选的，但是finally子句一经使用，其代码无论如何都会执行。  

    function testFinally() {
       try {
           return 2;
       } catch (error) {
           return 1;
       } finally {
           return 0;
       }
     }
     console.log(testFinally());
这个函数因为最后有finally的return 0；导致前面的语句会被忽略，只能返回0.  
如果提供了finally子句，则catch子句就成了可选的(catch或finally有一个即可)。  
### 错误类型
执行代码期间可能会发生的错误有多种类型。ES规定下列7种错误类型  
<li>Error
<li>EvalError
<li>RangeError
<li>ReferenceError
<li>SyntaxError
<li>TypeError
<li>URIError
### 合理使用try-catch
使用try-catch最适合处理那些我们无法控制的错误。假设你在使用一个大型的JavaScripot库中的函数，该函数可能会无意有意地抛出一些错误。我们可以将该函数的调用放在try-catch语句中，万一有什么错误发生，也好适当地处理他们。  

---
# 2.抛出错误 throw操作符
与try-catch语句相配的还有一个throw操作符，用于随时抛出自定义错误。抛出错误时，必须要给throw操作符指定一个值,这个值是什么类型，没有要求。e.g.    

    throw 12345;
    throw "hello world";
    throw true;
    throw {name:"JavaScript"};
在遇到throw操作符时，代码会立即停止执行，仅当有try-catch语句，捕获到被抛出的值时，代码才会继续执行。  
### 使用某种内置错误类型
可以更真实地模拟浏览器错误，每种错误类型的构造函数接受一个参数，即实际的错误消息。e.g.  

      throw new Error("something bad happen");
例如，throw一个错误  

      throw new RangeError("something bad happen");
       function testFinally() {
           try {

           } catch (error) {
               console.log(error.message);
           }
       }

![5HGXRu.png](https://s1.ax2x.com/2018/09/24/5HGXRu.png)  
### 此外，可以利用原型链来创建自定义的错误类型    


    function CustomError(message) {
      this.name = "CustomError";
      this.message = message;
    }
    CustomError.prototype = new Error();
    throw new CustomError("My message");
    function testFinally() {
      try {

        } catch (error) {
       console.log(error.message);
     }
    }
如果要捕获自己抛出的错误，并且把它与其他浏览器区别对待的话，创建自定义的错误还是很有用的。   
## 抛出错误的时机
要针对函数为什么会执行失败给出更多信息，抛出自定义错误是一种很方便的方式。应该在出现某种特定的已知错误条件，导致函数无法执行时，抛出错误。  

    function process(values) {
      //如果参数不是数组时，抛出错误
       if (!(values instanceof Array))
           throw new Error("process():Argument must be an array");
       values.sort();
       for (var i = 0; i < values.length; i++) {
           if (values[i] > 100)
               return values[i];
       }
       return -1;
     }
     try{
        process("hello");
       } catch (error) {
       console.log(error.message);
     }

![5HGVPA.png](https://s1.ax2x.com/2018/09/24/5HGVPA.png)  

建议在开发Javascript代码的过程中，重点关注函数和可能导致函数执行失败的因素，良好的错误处理机制应该可以确保代码只发生自己抛出的错误。  

---
# 错误事件
任何没有通过try-catch处理的错误都会触发window对象的error事件。
图像也支持error事件，只要图像的src特性中的URL不能返回可以被识别的图像格式，就会触发error事件。此时的error事件遵循DOM格式，返回一个以图像为目标的event对象。  

      var img = new Image();
      //指定不存在的文件
      img.src = "abc.jpg";
      img.onerror = function (message, url, line) {
          console.log("image not loaded");
      };
# 常见的错误类型
<li>类型转换错误
<li>数据类型错误
<li>通信错误
### 类型转换错误
1.在使用相等(==)和不相等(!=)操作符，或者在if,for以及while等控制语句中使用非布尔值时，最常发生转换错误。  

      alert(5=="5");//true
      alert(5==="5");//false
      alert(1==true);//true
      alert(1===true);//false

全等操作符知道要比较的是两种不同的数据类型，因而直接返回false。  
使用全等和非全等操作符，可以避免发生因为使用相等和不相等操作符引发的类型转换错误，因而强烈推荐使用。   

2.流控制语句   
像if之类的语句在确定下一步操作之前会自动把任何值转换成布尔值。尤其是if语句，如果使用不当，最容易出错。  

    function concat(str1,str2,str3){
      var result=str1+str2;
      if(str3)
      result+=str3;
      return result;
    }
这个函数的用意是拼接两个或三个字符串，然后返回结果。其中，第三个字符串是可选的，因此必须检查。但是，不是只有字符串值才可以转换成true，假设第三个参数是数值0，那么if语句的测试就会失败，而对数值1的测试就会通过。  
在流控制语句中使用非布尔值，是极为常见的一个错误来源。为避免此类错误，就要做到在条件比较时，切实传入布尔值。e.g.   

      function concat(str1,str2,str3){
        var result=str1+str2;
        //恰当的比较
        if(typeof str3=="string")
        result+=str3;

        return result;
      }
### 数据类型错误
为了保证不会发生数据类型错误，只能依靠开发人员i安歇适当的数据类型检测代码。  

    function getQueryString(url){
      var pos=url.indexOf("?");
      if(pos>-1)
      return url.substring(pos+1);
      return "";
    }
这个函数的用意是返回给定URL中的查询字符串，为此，它首先使用indexOf()寻找字符串中的问号，如果找到了，利用subString()方法返回问好后面的所有字符串。这个例子中的函数只能操作字符串，因此只要传入其他数据类型的值就会导致错误。因此  

    function getQueryString(url){
      //检测类型，如果是字符串，再去搜寻"?"后的字符
      if(typeof url=="string"){
        var pos=url.indexOf("?");
        if(pos>-1)
        return url.substring(pos+1);

      }
      return "";
    }
重写后的这个函数首先检查了传入的值是不是字符串。这样，就确保了函数不会以为接收到非字符串值而导致错误。  

    function reverseSort(values){
      //先检测一下，传入的是否为数组类型
      if(values instanceof Array){
        values.sort();
        values.reverse();
      }
    }
大体来说，基本类型的值应该使用typeof来检测，而对象的值则应该使用instanceof来检测。  面向公众的API则必须无条件地执行类型检查，以确保函数始终能够正常地执行。  
## 初始化多个模块  
如果程序中有多个模块需要初始化时

    for(var i=0,len=mods.length;i<len;i++){
      try{
        mods[i].init();  
      }catch(error){
        //在这里处理错误
      }
    }
在通过使用try-catch语句时，使得各个模块不会互相干扰，不会出现其中一个模块出现了问题，连带该模块以后的模块无法执行。  
## 把错误记录到服务器中
在复杂的web应用程序中，推荐把Javascript错误也写回到服务器。换句话说，也要把这些错误写入到保存服务器端错误的地方，只不过要注明他们来自前端。  

    function logError(sev,msg){
      var img=new Image();
      img.src="log.php?sev="+encodeURIComponent(sev)+"&msg="+encodeURIComponent(msg);
    }
这个logError()函数接受两个参数，表示严重程度的数字或字符串，以及错误的消息。其中，使用了image对象来发送请求，这样做非常灵活，任何浏览器都支持image对象。    

只要是使用try-catch语句，就应该把相应的错误记录到日志中。  

    for(var i=0,len=mods.length();i<len;i++){
      try{
        mods[i].init();
      }catch(error){
        logError("nonfatal","module init failed"+ex.message);
      }
    }
这里一旦初始化模块失败，就会调用logError()。第一个参数是"nonfatal"，表示非致命。第二个参数是真正的JS错误原因。  

----
# 调试技术
## 将消息记录到控制台
    var img = new Image();
     img.src = "abc.jpg";
     img.onerror = function (message, url, line) {
         console.error("将错误型消息记录到控制台中");
         console.warn("将警告型消息记录到控制台中");
         console.info("将消息性消息记录到控制台中");
         console.log("将一般消息记录到控制台中");
     };
![5HGaO3.png](https://s1.ax2x.com/2018/09/24/5HGaO3.png)  

记录消息要比使用alert()函数更可取，因为警告框会阻止程序的执行，而在测定异步处理对时间的影响时，使用警告框会影响结果。  

## 抛出错误

      function divide(num1, num2) {
      if (typeof num1 != "number" || typeof num2 != "number") {
          throw new Error("divide(): Both argument must be numbers");
      }
      return num1 / num2;
      }
      console.log(divide(2, 5));
      console.log(divide("ok", 2));
先检测两个数字，是否为number，否则就抛出错误  

<strong>对于大型应用，自定义的错误通常都使用assert()函数抛出  </strong>

    function assert(condition, message) {
    if (!condition) {
        throw new Error(message);
    }
    }

    function divide(num1, num2) {
    assert(typeof num1 != "number" || typeof num2 != "number", "divide(): Both argument must be numbers");
    return num1 / num2;
    }
    console.log(divide(2, 5));
    console.log(divide("ok", 2));
以上就是个非常基本的assert()函数。可见，使用assert函数代替某些需要测试的if语句，可以减少抛出错误所需要的代码量。  
